'use client';

import React, { useState, useRef, useEffect } from 'react';
import { Send, Bot, User, Sparkles, Cpu, ShieldCheck, ChevronRight } from 'lucide-react';


interface Message {
  role: 'user' | 'agent';
  text: string;
}

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'agent',
      text: "Welcome to the Acme Corp Quantum Technical Portal. I am your Acme QuantumWidget v4.2 RAG Knowledge Assistant. You can ask me specific configuration, installation, or troubleshooting questions based on our internal documentation."
    }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to the bottom of the chat viewport
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const handleSend = async (messageText?: string) => {
    const query = (messageText || input).trim();
    if (!query || loading) return;

    if (!messageText) {
      setInput('');
    }

    // Append user message
    setMessages((prev) => [...prev, { role: 'user', text: query }]);
    setLoading(true);

    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: query }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || `HTTP error ${response.status}`);
      }

      const data = await response.json();
      
      // Append agent response
      setMessages((prev) => [
        ...prev,
        { role: 'agent', text: data.response || "No response generated by the assistant." }
      ]);
    } catch (err: any) {
      setMessages((prev) => [
        ...prev,
        { role: 'agent', text: `An error occurred: ${err.message || 'Unable to fetch response.'}` }
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      handleSend();
    }
  };

  const presetQuestions = [
    {
      title: "Troubleshoot E-404",
      desc: "Steps to fix red light phase de-alignment",
      query: "How do I fix flashing red light error code E-404?"
    },
    {
      title: "Operating Conditions",
      desc: "Target operating temperatures",
      query: "What is the optimal operating temperature for QuantumWidget?"
    },
    {
      title: "Helium Flow Settings",
      desc: "Helium cryo-coolant levels",
      query: "What is the recommended helium flow rate?"
    },
    {
      title: "Warranty Limits",
      desc: "Verify installation rules",
      query: "Does the warranty cover damage from magnetic tools?"
    }
  ];

  return (
    <div className="flex flex-col flex-1 h-screen bg-slate-950 text-slate-100">
      {/* Header */}
      <header className="border-b border-slate-900 bg-slate-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="bg-indigo-600/20 text-indigo-400 p-2 rounded-xl border border-indigo-500/20 shadow-indigo-500/10 shadow-lg">
              <Cpu className="w-6 h-6 animate-pulse" />
            </div>
            <div>
              <h1 className="text-lg font-bold bg-gradient-to-r from-indigo-200 via-indigo-400 to-indigo-200 bg-clip-text text-transparent">
                Acme QuantumWidget Support
              </h1>
              <p className="text-xs text-slate-400 flex items-center gap-1">
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                RAG Pipeline Connected
              </p>
            </div>
          </div>
          <div className="flex items-center space-x-2 text-xs bg-slate-900 border border-slate-800 rounded-lg py-1.5 px-3">
            <span className="text-slate-400 font-mono">Model:</span>
            <span className="text-indigo-400 font-mono font-medium">gemini-1.5-flash</span>
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 flex flex-col max-w-4xl w-full mx-auto p-4 overflow-hidden">
        {/* Chat Area */}
        <div className="flex-1 overflow-y-auto pr-2 mb-4 space-y-6">
          {messages.map((msg, index) => (
            <div
              key={index}
              className={`flex w-full ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              <div className={`flex items-start gap-3 max-w-[80%] ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
                {/* Avatar */}
                <div className={`flex-shrink-0 p-2 rounded-lg border ${
                  msg.role === 'user'
                    ? 'bg-indigo-600 text-white border-indigo-500'
                    : 'bg-slate-900 text-indigo-400 border-slate-800'
                }`}>
                  {msg.role === 'user' ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
                </div>

                {/* Message Bubble */}
                <div className={`rounded-2xl px-4 py-3 shadow-md border ${
                  msg.role === 'user'
                    ? 'bg-indigo-600/15 border-indigo-500/30 text-indigo-50'
                    : 'bg-slate-900/60 border-slate-800/80 text-slate-200'
                }`}>
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">{msg.text}</p>
                </div>
              </div>
            </div>
          ))}

          {/* Loading Indicator */}
          {loading && (
            <div className="flex w-full justify-start">
              <div className="flex items-start gap-3 max-w-[80%]">
                <div className="flex-shrink-0 p-2 rounded-lg border bg-slate-900 text-indigo-400 border-slate-800">
                  <Bot className="w-4 h-4 animate-spin" />
                </div>
                <div className="rounded-2xl px-4 py-3 shadow-md border bg-slate-900/60 border-slate-800/80 text-slate-400">
                  <div className="flex items-center space-x-1.5 py-1">
                    <span className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></span>
                    <span className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></span>
                    <span className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></span>
                  </div>
                </div>
              </div>
            </div>
          )}

          <div ref={chatEndRef} />
        </div>

        {/* Preset/Suggestion Questions */}
        {messages.length === 1 && !loading && (
          <div className="mb-6 animate-fade-in">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-3 flex items-center gap-1.5">
              <Sparkles className="w-3 h-3 text-indigo-400" />
              Suggested Operations
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {presetQuestions.map((item, idx) => (
                <button
                  key={idx}
                  onClick={() => handleSend(item.query)}
                  className="text-left bg-slate-900/40 hover:bg-slate-900 border border-slate-800/60 hover:border-indigo-500/40 p-3.5 rounded-xl transition duration-200 group flex items-start justify-between"
                >
                  <div className="pr-2">
                    <h3 className="text-xs font-semibold text-indigo-300 group-hover:text-indigo-200">
                      {item.title}
                    </h3>
                    <p className="text-xs text-slate-400 mt-1">
                      {item.desc}
                    </p>
                  </div>
                  <ChevronRight className="w-4 h-4 text-slate-500 group-hover:text-indigo-400 transition flex-shrink-0 mt-0.5" />
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Input Form */}
        <div className="sticky bottom-0 bg-slate-950 pt-2 pb-4">
          <div className="relative flex items-center bg-slate-900/60 border border-slate-800 focus-within:border-indigo-500/60 rounded-xl px-4 py-2.5 shadow-2xl transition">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              disabled={loading}
              placeholder="Ask a question about Acme QuantumWidget v4.2..."
              className="flex-1 bg-transparent text-sm border-none outline-none focus:ring-0 text-slate-200 placeholder-slate-500 pr-12 disabled:opacity-50"
            />
            <button
              onClick={() => handleSend()}
              disabled={loading || !input.trim()}
              className="absolute right-2.5 p-2 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-600 text-white rounded-lg transition duration-200 flex items-center justify-center shadow-lg shadow-indigo-600/10"
            >
              <Send className="w-4 h-4" />
            </button>
          </div>
          <p className="text-[10px] text-center text-slate-500 mt-2 flex items-center justify-center gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5 text-indigo-500/70" />
            Internal operations system. Answers are sourced strictly from Acme knowledge_base.txt.
          </p>
        </div>
      </main>
    </div>
  );
}
